=== TaskForce47/TF47-API/TF47_Api/wwwroot/squadxml/squad.dtd
<!ELEMENT squad (name, email, web?, picture?, title?, member+)>
<!ATTLIST squad nick CDATA #REQUIRED>

<!ELEMENT member (name, email, icq?, remark?, picture?, steamid?)>
<!ATTLIST member id CDATA #REQUIRED nick CDATA #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT icq (#PCDATA)>
<!ATTLIST icq href CDATA #IMPLIED>
<!ELEMENT steamid (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!ELEMENT remark (#PCDATA)>
<!ELEMENT picture (#PCDATA)>
<!ELEMENT title (#PCDATA)>

=== TaskForce47/TF47-API/TF47-API/wwwroot/squadxml/1/squad.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../squad.xsl" ?>
<!DOCTYPE squad SYSTEM "squad.dtd">
<squad nick="TF47-S">
	<name>TF47-Stammspieler</name>
	<email>taskforce47@web.de</email>
	<web>https://taskforce47.com</web>
	<picture>logo.paa</picture>
	<title>TF47-Stammspieler</title>
	<member id="76561198023782694" nick="Dragon">
		<name>Dragon</name>
		<email>string</email>
		<icq>N/A</icq>
		<remark>string</remark>
	</member>
</squad>
